---
data_input: 'data/pcos.T.csv'
log_transform: true
method: 'sparcc'
n_iteractions: 20
name: 'pcos_sparCC'
name_output_file: 'sparcc_test_version_kambucha'
normalization: 'dirichlet'
num_simulate_data: 100
outfile_pvals: 'src/pcos_pvals_one_sided.csv'
outpath: 'src/pvals/'
perm_template: 'permutation_#.csv'
save_corr_file: 'src/pcos_sparcc.csv'
save_cov_file:
threshold: 0.1
type_pvalues: 'one_sided'
x_iteractions: 10
